# Generated by Django 5.2.8 on 2025-11-26 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to="bot_app.city",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to="bot_app.city",
            ),
        ),
    ]
