# Generated by Django 5.2.8 on 2025-11-26 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_app", "0002_place_city"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "City", "verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="guide",
            options={"verbose_name": "Guide", "verbose_name_plural": "Guides"},
        ),
        migrations.AlterModelOptions(
            name="place",
            options={"verbose_name": "Place", "verbose_name_plural": "Places"},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Review", "verbose_name_plural": "Reviews"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Bot user", "verbose_name_plural": "Bot users"},
        ),
        migrations.AlterField(
            model_name="place",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to="bot_app.category",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="location",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
